spring:
  #\u914D\u7F6Ees\u8FDE\u63A5\u4FE1\u606F,\u914D\u7F6E\u540E\u53EF\u4EE5\u5728\u4EE3\u7801\u4E2D\u4F7F\u7528 @Autowired\u6CE8\u89E3\u6CE8\u5165RestHighLevelClient\u5BF9\u8C61
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9001,http://127.0.0.1:9002,http://127.0.0.1:9003

server:
  port: 9090

ffmpeg:
   dir: ${user.dir}/ffmpeg
